# the default speed for mouse movement and scrolling
baseMouseSpeed: 630.0
baseScrollSpeed: 20.0

comboTime: 120 

# the rest of the config defines the layers with their bindings
layers:
# the first layer is active at start
- name: initial
  bindings:
    rightalt+k: layer mouse 

- name: mouse
  bindings:
    q: layer initial
    esc: layer initial
    r: reload-config   

    left: move -1  0
    down: move  0  1
    up: move  0 -1
    right: move  1  0
    
    i: scroll up
    u: scroll down
    y: scroll right 
    o: scroll left
    
    s: speed 3.0
    a: speed 0.2
    
    f: button left
    g: button right
